README: Bump JWS version to latest, 5.7, in README.
ansible-middleware/jws pull request #204
Opened 2022-11-08 11:31 UTC by rpelisse

@csutherl as suggested again by Adam, we should bump the version of JWS to 5.7 in the README.

2022-11-08 11:40 UTC, rpelisse commented
Gosh, I meant to do that too indeed... Brain of :tropical_fish: today... Let me fix that up. Thanks for noticing this.

2022-11-08 11:48 UTC, rpelisse commented
@defeatedbylife Done! But please double check if you can (I'm still a :fish: today)

2022-11-09 08:14 UTC, rpelisse commented
@defeatedbylife Thanks, you are a life saver! I really had a bad case of :fish: brain yesterday (more than usual). I've fixed up all of this, but I trust @csutherl to keep me honest on the versions for Tomcat and the native bits. 

Regarding rhn_ids, you are right, but I'll set up another PR once this one is merged.

2022-11-10 20:31 UTC, csutherl requested changes
+1 after you fix the release date.

2022-11-10 20:31 UTC, csutherl commented on roles/jws/README.md
> +|`5.7.0`      |November 11, 2022  |`9.0.62`        | `1.2.31`        |[Release Notes](https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server/5.7/html/red_hat_jboss_web_server_5.7_rele
The release date is November 2, not tomorrow :smile:

2022-11-11 07:26 UTC, rpelisse commented on roles/jws/README.md
> +|`5.7.0`      |November 11, 2022  |`9.0.62`        | `1.2.31`        |[Release Notes](https://access.redhat.com/documentation/en-us/red_hat_jboss_web_server/5.7/html/red_hat_jboss_web_server_5.7_rele
[88 miles per hour!!!!!](https://media.tenor.com/EyCsxMiZQhIAAAAC/delorean-back-to-the-future.gif)

2022-11-11 07:50 UTC, merged