Fix linting and refactor incosistencies
ansible-middleware/jws pull request #246
Opened 2023-10-06 13:16 UTC by dsoumis

- Fix linting errors and warnings which were occurring in Github workflows.
- Refactor strings for consistency and update jws5 version being used to the latest one (hard coded).
- Simplify fastpackage.yml

2023-10-06 13:54 UTC, dsoumis commented
I guess for the checks to fail there is currently some inconsistency between the PR and main branch.
Checks pass successfully with the changes applied to my [fork](https://github.com/dsoumis/jws/actions/runs/6432386534).

2023-10-06 15:48 UTC, rpelisse commented on roles/jws/tasks/fastpackage.yml
> +    - package_name is defined
@dsoumis That may seems weird, but rpm -q is WAY faster than yum to ascertain if a package is installed. Also, I would like to keep the assert: because if fastpackage is used, the package_name should be provided. Allowing fast package to be called with no package name (and silently skipping) is not IMHO a good behavior.

2023-10-06 15:57 UTC, rpelisse commented on roles/jws/tasks/systemd/seport.yml
> +    - result.rc == 0
nice catch!

2023-10-06 15:58 UTC, rpelisse requested changes
I spot a few things that might need to be changed, but I'll suggest to wait that @guidograzioli also did his review.

2023-10-09 10:17 UTC, rpelisse commented on .github/workflows/docs.yml
> +      pages: write
@dsoumis discuss this with @guidograzioli and we are not clear of the intent.

2023-10-10 06:55 UTC, guidograzioli commented on .github/workflows/docs.yml
> +      pages: write
It's the same set of permissions set in the [called](https://github.com/ansible-middleware/github-actions/blob/main/.github/workflows/docs.yml#L21) workflow, not sure we need them in here too

2023-10-10 06:58 UTC, guidograzioli commented on roles/jws/tasks/main.yml
> +    jws_dependencies_list: "[ {{ jws_dependencies_list }} + {{ jws_firewalld_package_name }} ]"
jws_dependencies*_list* definitely wants to be a list; also the second syntax is looking for trouble imho

2023-10-10 06:59 UTC, guidograzioli commented on roles/jws/tasks/fastpackage.yml
> +    - package_name is defined
we have a much newer version of fastpackages in other collection, we need to port it here (it executes a single rpm command with the whole package list)

2023-10-10 07:01 UTC, guidograzioli commented on roles/jws/tasks/fastpackage.yml
> +    - package_name is defined
this: https://github.com/ansible-middleware/infinispan/blob/main/roles/infinispan/tasks/fastpackages.yml
it takes the list directly, does not need to be called in a loop

2023-10-10 07:02 UTC, guidograzioli commented
> I spot a few things that might need to be changed, but I'll suggest to wait that @guidograzioli also did his review.

Agree with your requested changes

2023-10-10 07:03 UTC, rpelisse commented
@dsoumis Guido and I review your PR. There is a bit too much different changes in it... Would you mind filling again those changes, in separate PRs, so we can more atomically merge them? Thanks! :)

2023-10-10 08:03 UTC, dsoumis commented
Closing this and will introduce the changes to new more atomic PRs. :)

2023-10-10 08:03 UTC, closed without merging