Determine if offline patch is available
ansible-middleware/jws pull request #290
Opened 2024-11-28 14:28 UTC by guidograzioli

2024-11-28 14:30 UTC, rpelisse approved these changes
LGTM!

2024-11-28 14:37 UTC, jajik requested changes

2024-11-28 14:37 UTC, jajik commented on roles/jws/tasks/apply_cp/apply_cp.yml
> +        src: "{{ jws_archive_repository }}/{{ patch_bundle }}"
This does not look right, even linter is complaining...

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html

2024-11-28 14:38 UTC, guidograzioli commented on roles/jws/tasks/apply_cp/apply_cp.yml
> +        src: "{{ jws_archive_repository }}/{{ patch_bundle }}"
yup

2024-12-12 12:00 UTC, rpelisse approved these changes
@guidograzioli LGTM!

2024-12-12 12:10 UTC, merged